### ISSUE TITLE
LeftIcon Crashes Xaml Previewer

### ISSUE THREAD

**Issue by montehansen** [LeoJHarris/AdvancedEntry#10]
I had a typo in the LeftIcon property and it crashed the xaml previewer. I assume because there is no exception handling in there =]

**Comment by LeoJHarris** [comment]
Possibly not, I'm also open to PR if anyone wants to improve the library further. I think this would be small change to implement some better exception handling.

Although within the code which you can see I am checking the leftIcon:

`if (!string.IsNullOrEmpty(entryExt.LeftIcon))
                    {
                        int identifier = Context.Resources.GetIdentifier(
                            entryExt.LeftIcon,
                            "drawable",
                            PackageName);
                        if (identifier != 0)
                        {
                            Drawable drawable = Resources.GetDrawable(identifier);
                            if (drawable != null)
                            {
                                Control.SetCompoundDrawablesWithIntrinsicBounds(drawable, null, null, null);
                                Control.CompoundDrawablePadding = entryExt.PaddingLeftIcon;
                            }
                        }`

 By the way the Xamarin Live Preview is as bugger as heck, so the issue could lay in that as well.

**Comment by montehansen** [comment]
Thanks,

 

Are you open to PRs for feature changes? Specifically, I would like to change the interface of IconLeft to : Icon + IconLocation (which would be an enum of Left or Right).

 

Monte

**Comment by LeoJHarris** [comment]
Yup that would be fine. Create a branch for this. PR once that's done. Ill review and merge afterwards.

**Comment by LeoJHarris** [comment]
Last I was at with this lib I was working on a toggle for password between show and I hide and I have been meaning on completing that which I might do some additional stuff on that this weekend coming

**Comment by LeoJHarris** [comment]
Hi there, I noticed the project was not building, there was a reference to an old version of Xamarin.Forms.2.5.1.444934 in the SampleApp.Android.csporj. I have resolved the issue and also updated to latest Xamarin.Forms.3.1.0.697729

You can do a fetch and pull on the repo.

**Comment by montehansen** [comment]
Yeah I noticed that too. Thanks I will pull again.

**Comment by LeoJHarris** [comment]
Cool any questions or issues let me know. Thanks
