### ISSUE TITLE
Height is hard coded on iOS

### ISSUE THREAD

**Issue by lhughey** [LeoJHarris/AdvancedEntry#13]
Thanks for providing such a great control. The height is hardcoded to 30 in iOS and is does not change, but is adjustable in Android.

**Comment by LeoJHarris** [comment]
@lhughey I can removed the hard coded height. Cant recall exactly why that was set.

**Comment by lhughey** [comment]
Thanks for the quick update, Leo and the awesome work you've done on this library. It is a great help to the community.

**Comment by LeoJHarris** [comment]
@lhughey will do a new release on this tomorrow. I had added a bindable property for entry height otherwise it uses the hard coded value. Thanks for your feedback 👍

**Comment by LeoJHarris** [comment]
@lhughey https://www.nuget.org/packages/LeoJHarris.XForms.Plugin.EnhancedEntry/1.0.3
