### ISSUE TITLE
Funcionallity of keyboard

### ISSUE THREAD

**Issue by filycoronado** [LeoJHarris/AdvancedEntry#4]
the keyboard always open , but never close when the user press "done" in the keyboard i dont understand what configuration need it  
![image](https://user-images.githubusercontent.com/34321433/33687908-eb8ffbd8-da96-11e7-834a-988307f02d65.png)

**Comment by LeoJHarris** [comment]
So i have implemented functionality to close the keyboard, however this affects closing the keyboard when it should stay open if a user moves moves to another entry on 'next' keyboard command which gives focus to the next entry. So I will fix that and add a new build on nuget.

**Comment by filycoronado** [comment]
thank you So much  LeoJHarris   i will wait  a new compilation in nuget   :)  the plugin is cool only have a little details :D  
Cheers !

**Comment by LeoJHarris** [comment]
Hi i have added new build to nuget and it should work I have tested, please let me know if you are seeing the same. Closes keyboard on DONE. Thanks. The component is renamed to EnhancedEntry

**Comment by filycoronado** [comment]
Hi  LeoJHarris    the plugin working great  :D Thanks   !!!
