### ISSUE TITLE
support net standard

### ISSUE THREAD

**Issue by Shaboo** [LeoJHarris/AdvancedEntry#5]
when is it expected that the library support net standard?

thanks for the great library

**Comment by LeoJHarris** [comment]
That i can look into so possibly in this month. Glad you find the lib useful.

**Comment by LeoJHarris** [comment]
I have setup library to support net standard in latest release version 1.0.9

**Comment by LeoJHarris** [comment]
As some body correctly pointed out the forms part is missing in the nuget package, will resolve this issue shortly and close the issue

**Comment by LeoJHarris** [comment]
Hi @Shaboo have added .net standard 2.0 support to the library. Am waiting on a new mac machine to actually do a new build for that. Hopefully get that soon.

**Comment by Shaboo** [comment]
@LeoJHarris thank you very much,
actually I have done that locally(just for me), by re-create it in my device and target .net standard,
thank you again for you concern

**Comment by LeoJHarris** [comment]
Sorry this took so long have added new version with .net standard 2.0 support... feel free to do a pull request next time :)
