### ISSUE TITLE
Missing dll in netstandard1.0 folder in Nuget Package

### ISSUE THREAD

**Issue by jesulink2514** [LeoJHarris/AdvancedEntry#6]
Your package does not contain the Forms part of this control, the netstandard1.0 folder is empty.

**Comment by LeoJHarris** [comment]
Hi @jesulink2514 I will check the configuration and I will add a new version to nuget which will include the forms part shortly.

**Comment by LeoJHarris** [comment]
Hi @jesulink2514 have added .net standard 2.0 support to the library and is included in the forms part. Am waiting on a new mac machine to actually do a new build for that. Hopefully get that soon.

**Comment by LeoJHarris** [comment]
Sorry this took so long have added a new version with .net standard 2.0 in version 1.0.1 on nuget
