### ISSUE TITLE
need to be able to change the images

### ISSUE THREAD

**Issue by al3xmeister** [LeoJHarris/AdvancedEntry#9]
Hi Leo, 

My project has got quite a dark background and I would really love to be able to replace the icons with much lighter ones that I already have - could you please let me know how I can achieve that? Many thanks in advance and great work on the plugin

**Comment by LeoJHarris** [comment]
Hi @al3xmeister  you should be able to use difference images (lighter). Simply add the images you want to your respective drawable folders on android and the images for iOS as well. 

Then set the LeftIcon property of the EnhancedEntry to the name of the image you have placed in these and it should be okay.

**Comment by al3xmeister** [comment]
that's great, but how would I then be able to set it to a different image once it's clicked? will it not show the same image.png? thanks again @LeoJHarris

**Comment by LeoJHarris** [comment]
Can you try to set the lefticon in the click event to another image? From your original question you only wanted to change the image to something lighter?

**Comment by al3xmeister** [comment]
@LeoJHarris I think I was misunderstood. I've managed to set up different images as the left icon property, however what I'm interested in is changing the hidden password effect icon. That one is quite dark and my app already has a dark background. any way I could replace it in a few lines of code?

**Comment by al3xmeister** [comment]
any joy Sir?

**Comment by al3xmeister** [comment]
I managed to sort it out, thanks for your extension anyway
